sudo: required
services:
  - docker

before_install:
  - docker build -t guidosantillan01/react-test -f ./client/Dockerfile.dev ./client # ./client is the build context

script:
  - docker run -e CI=true guidosantillan01/react-test npm run test

after_success:
  - docker build -t guidosantillan01/multi-client ./client # ./client is the build context
  - docker build -t guidosantillan01/multi-nginx ./nginx
  - docker build -t guidosantillan01/multi-server ./server
  - docker build -t guidosantillan01/multi-worker ./worker

  # Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images to the Docker Hub
  - docker push guidosantillan01/multi-client
  - docker push guidosantillan01/multi-nginx
  - docker push guidosantillan01/multi-server
  - docker push guidosantillan01/multi-worker

deploy:
  provider: elasticbeanstalk
  region: sa-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-sa-east-1-570620208014
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
